# Generated by Django 3.2.7 on 2021-09-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210928_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['date_posted']},
        ),
    ]
