# Generated by Django 3.2.7 on 2021-10-21 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20211014_1157'),
        ('contact', '0003_auto_20211020_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_response', models.CharField(default='#d7880d', max_length=50)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_notification', to='profiles.profile')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_notification', to='profiles.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
